/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CutoffsRouteImport } from './routes/cutoffs'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutesInstituteRouteImport } from './routes/institutes.$institute'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CutoffsRoute = CutoffsRouteImport.update({
  id: '/cutoffs',
  path: '/cutoffs',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesInstituteRoute = InstitutesInstituteRouteImport.update({
  id: '/institutes/$institute',
  path: '/institutes/$institute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRoute
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/predictor': typeof PredictorRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/$institute': typeof InstitutesInstituteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRoute
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/predictor': typeof PredictorRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/$institute': typeof InstitutesInstituteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colleges': typeof CollegesRoute
  '/cutoffs': typeof CutoffsRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/predictor': typeof PredictorRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/institutes/$institute': typeof InstitutesInstituteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/colleges'
    | '/cutoffs'
    | '/dashboard'
    | '/faqs'
    | '/predictor'
    | '/resources'
    | '/sitemap.xml'
    | '/institutes/$institute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/colleges'
    | '/cutoffs'
    | '/dashboard'
    | '/faqs'
    | '/predictor'
    | '/resources'
    | '/sitemap.xml'
    | '/institutes/$institute'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/colleges'
    | '/cutoffs'
    | '/dashboard'
    | '/faqs'
    | '/predictor'
    | '/resources'
    | '/sitemap.xml'
    | '/institutes/$institute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CollegesRoute: typeof CollegesRoute
  CutoffsRoute: typeof CutoffsRoute
  DashboardRoute: typeof DashboardRoute
  FaqsRoute: typeof FaqsRoute
  PredictorRoute: typeof PredictorRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InstitutesInstituteRoute: typeof InstitutesInstituteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cutoffs': {
      id: '/cutoffs'
      path: '/cutoffs'
      fullPath: '/cutoffs'
      preLoaderRoute: typeof CutoffsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes/$institute': {
      id: '/institutes/$institute'
      path: '/institutes/$institute'
      fullPath: '/institutes/$institute'
      preLoaderRoute: typeof InstitutesInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CollegesRoute: CollegesRoute,
  CutoffsRoute: CutoffsRoute,
  DashboardRoute: DashboardRoute,
  FaqsRoute: FaqsRoute,
  PredictorRoute: PredictorRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InstitutesInstituteRoute: InstitutesInstituteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
